version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: estadio_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lilly12@
      POSTGRES_DB: estadio_postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: